require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'DemosThing' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-razorpay', :path => '../node_modules/react-native-razorpay'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  target 'DemosThingTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'DemosThing-tvOS' do
  # Pods for DemosThing-tvOS

  target 'DemosThing-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
